services:
  postgres:
    container_name: gophermart-db
    image: postgres:17-alpine
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
volumes:
  db:
