services:
  gophermart:
    image: ghcr.io/lekcrg/gophermart:latest
    container_name: gophermart-backend
    ports:
      - 80:8080
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
  accrual:
    image: ghcr.io/lekcrg/gophermart-accrual:latest
    container_name: gophermart-accrual
    restart: unless-stopped
    ports:
      - 8888:8888