services:
  gophermart:
    container_name: gophermart-backend
    build:
      dockerfile: ./docker/Dockerfile.gophermart
    ports:
      - 80:8080
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env.docker
  accrual:
    build:
      dockerfile: ./docker/Dockerfile.accrual
    container_name: gophermart-accrual
    restart: unless-stopped
    ports:
      - 8888:8888
    env_file:
      - .env.docker