name: docker build

on:
  workflow_dispatch:
  workflow_run:
    workflows: [build, statictest]
    branches:
      - main
      - master
      - docker
    types:
      - completed

jobs:
  docker-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile.gophermart
          platforms: linux/amd64
          push: true
          tags: LekcRg/gophermart:latest
      - name: Copy files via SSH
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          source: "docker-compose.yml,docker-compose.production.yml"
          target: gophermart-actions
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd gophermart-actions
            docker pull ghcr.io/LekcRg/gophermart:latest
            docker compose -f docker-compose.production.yml up -d --build